name: qtf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
    - annotated-types==0.7.0
    - black==25.1.0
    - cfgv==3.4.0
    - click==8.2.1
    - distlib==0.4.0
    - filelock==3.19.1
    - identify==2.6.14
    - iniconfig==2.1.0
    - mypy_extensions==1.1.0
    - nodeenv==1.9.1
    - numpy==2.3.3
    - packaging==25.0
    - pandas==2.3.2
    - pandera==0.26.1
    - pathspec==0.12.1
    - platformdirs==4.4.0
    - plotly==6.3.0
    - pluggy==1.6.0
    - pre_commit==4.3.0
    - pydantic==2.11.9
    - pydantic_core==2.33.2
    - Pygments==2.19.2
    - pytest==8.4.2
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - PyYAML==6.0.2
    - ruff==0.13.0
    - setuptools==78.1.1
    - six==1.17.0
    - typeguard==4.4.4
    - typing-inspect==0.9.0
    - typing-inspection==0.4.1
    - typing_extensions==4.15.0
    - tzdata==2025.2
    - virtualenv==20.34.0
    - wheel==0.45.1
